apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teaching-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/humbeatbox/Teaching-Platform-Infra.git
    targetRevision: HEAD
    path: kubernetes/apps/teaching-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: teaching-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
