apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teaching-platform-external-secret
  namespace: teaching-platform
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: teaching-platform-secrets
    creationPolicy: Owner
  data:
  - secretKey: PASSPORT_SECRET
    remoteRef:
      key: teaching-platform/passport-secret
      property: PASSPORT_SECRET
