apiVersion: v1
kind: Service
metadata:
  name: teaching-platform
  namespace: teaching-platform
  labels:
    app: teaching-platform
spec:
  type: NodePort
  selector:
    app: teaching-platform
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
